### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FatherGotNoMilk** [Cattn/gba#47] opened 2023-01-26 14:01 UTC
**Describe the bug**
The bug is that when I go to some of the games, mainly Pokemon, I see that my Chromebook can't read the game and it just shows a menu and i can't access the games

**To Reproduce**
1. Go to cattn.github.io/gba/
2. Click on GameBoy emulators
3. Click GBA
4. Click 2nd page
5. Type fusion
6. Scroll down to Fusion-3-Red-Blue
7. See error

**Expected behavior**
I go to the game it has the normal loading screen and then it opens to the menu saying that it couldn't read the file

**Screenshots**
https://docs.google.com/document/d/15ywxnQ2U2E8falufI9vG9wm-10J0aG438RapVMvxR9k/edit?usp=sharing
Link to a docs with the pictures.

**Windows Or Chromebook?**
I am on Chromebook

**Additional context**
I tried doing this several times doing things in the menu but nothing worked. I think it is also a problem with my device because my friends can go onto the game and use it just fine. I also tried it for blazing emerald and it didn't work for that either.

**Comment by Cattn** [comment] 2023-01-26 14:09
Thank you for submitting a bug report, this issues is due to the roms just being bad, we will get new Roms/Patch new ones and add them soon, @Nailington may be on this. we will close when we complete it

**Comment by Nailington** [comment] 2023-01-26 16:18
@FatherGotNoMilk and @Cattn: I tried opening the game before doing any editing, and I see no issues?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/111466491/214889678-4b43bd2b-cb2e-4c50-b54d-df85b8d8d802.png">

**Comment by FatherGotNoMilk** [comment] 2023-01-26 19:25
This is what i though would happen it might just be a problem with my device because as stated my friends could access the game too.

**Comment by Cattn** [comment] 2023-01-26 19:36
Yeah that's a really weird bug, make sure you are on the new version of the GBA Emulator, otherwise i'm not sure I'm gonna close this as It seems to be device specific, and not a bug

**Closed by Cattn** 2023-01-26 19:36 UTC
Labels: bug
